export enum PAYMENT_STATUS {
    ON_PROGRESS = 'ON_PROGRESS',
    SUCCEEDED = 'SUCCEEDED',
    FAILED = 'FAILED',
    // REFUNDING = 'REFUNDING',
    // REFUND_SUCCEEDED = 'REFUND_SUCCEEDED',
    // REFUND_FAILED = 'REFUND_FAILED',
}