export enum GATEWAY_EXCEPTION {
    CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',
    START_FINDING_UNAVAILABLE = 'START_FINDING_UNAVAILABLE',
    STOP_FINDING_CONFLICT = 'STOP_FINDING_CONFLICT',
    QUEUE_INVALID_TOKEN = 'QUEUE_INVALID_TOKEN',
    STOP_CALLING_CONFLICT = 'STOP_CALLING_CONFLICT',
    PEERING_CONFLICT = 'PEERING_CONFLICT',
    QUESTIONAIRE_REQUEST_CONFLICT = 'QUESTIONAIRE_REQUEST_CONFLICT',
    QUESTIONAIRE_REJECT_CONFLICT = 'QUESTIONAIRE_REJECT_CONFLICT',
    QUESTIONAIRE_SUBMIT_CONFLICT = 'QUESTIONAIRE_SUBMIT_CONFLICT',
    NON_EXIST_CLIENT = 'NON_EXIST_CLIENT',
}
